[project]
name = "data-viber"
version = "0.1.0"
description = "Data viber is your chill repo for data collection and vibe checks."
authors = [
    {name = "davidberenstein1957", email = "david.m.berenstein@gmail.com"},
]
requires-python = ">=3.9,<3.13"
readme = "README.md"
license = {text = "Apache 2.0"}
dependencies = [
    "gradio[oauth]>=4.3,<5",
    "datasets>=2,<3",
]

[project.optional-dependencies]
"explorer" = [
    "sentence-transformers>=3",
    "umap-learn>=0.5,<1",
    "plotly>=5,<6",
    "dash>=2.11,<3",
]
annotator = [
    "openpyxl>=3.1.5",
]

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.8.0",
    "ruff>=0.5,<1",
    "pytest>=8,<9",
    "black>=24,<25",
    "transformers>=4",
    "torch>=2",
    "openpyxl>=3,<4",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88

[tool.pdm]
distribution = true

